---
- name: Prepare Storage for SP Server
  ansible.builtin.include_tasks: storage_prepare_linux.yml
  when: cleanup == false

- name: Cleanup storage
  ansible.builtin.include_tasks: storage_cleanup_linux.yml
  when: cleanup == true
