dsm_opt_parameters:
  dsm_opt_servername: ""
  dsm_opt_nodename: ""
#  dsm_opt_passwordaccess: ""
  dsm_opt_password: ""
  dsm_opt_domain: ""
#  dsm_opt_include_patterns: ""
#  dsm_opt_exclude_patterns: ""
#  dsm_opt_managedservices: ""
#  dsm_opt_schedlogname: ""
#  dsm_opt_errorlogname: ""
#  dsm_opt_compression: ""
#  dsm_opt_resourceutilization: ""
#  dsm_opt_tcpbuffsize: ""
#  dsm_opt_tcpwindowsize: ""
#  dsm_opt_httpport: ""
  dsm_opt_afmskipuncachedfiles: ""
  dsm_opt_archsymlinkasfile: ""
  dsm_opt_asnodename: ""
  dsm_opt_autodeploy: ""
  dsm_opt_automount: ""
  dsm_opt_collocatebyfilespec: ""
  dsm_opt_compressalways: ""
  dsm_opt_dedupcachepath: ""
  dsm_opt_dedupcachesize: ""
  dsm_opt_deduplication: ""
  dsm_opt_diffsnapshotname: ""
  dsm_opt_disablenqr: ""
  dsm_opt_efsdecrypt: ""
  dsm_opt_enablededupcache: ""
  dsm_opt_followsymbolic: ""
  dsm_opt_exclude_dedup: ""
  dsm_opt_lanfreessl: ""
  dsm_opt_lanfreetcpserveraddress: ""
  dsm_opt_makesparsefile: ""
  dsm_opt_mbobjrefreshthresh: ""
  dsm_opt_mbpctrefreshthreshold: ""
  dsm_opt_memoryefficientbackup: ""
  dsm_opt_memoryefficientbackup_diskcachem: ""
  dsm_opt_nfstimeout: ""
  dsm_opt_num: ""
  dsm_opt_preservelastaccessdate: ""
  dsm_opt_quiet: ""
  dsm_opt_quotesareliteral: ""
  dsm_opt_replace: ""
  dsm_opt_scrolllines: ""
  dsm_opt_scrollprompt: ""
  dsm_opt_setwindowtitle: ""
  dsm_opt_skipacl: ""
  dsm_opt_skipaclupdatecheck: ""
  dsm_opt_snapdiffchangelogdir: ""
  dsm_opt_srvoptsetencryptiondisabled: ""
  dsm_opt_sslfipsmode: ""
  dsm_opt_sslrequired: ""
  dsm_opt_stagingdirectory: ""
  dsm_opt_subdir: ""
  dsm_opt_tapeprompt: ""
  dsm_opt_timeformat: ""
  dsm_opt_updatectime: ""
  dsm_opt_verbose: ""
  dsm_opt_vmbackdir: ""
  dsm_opt_vmchost: ""
  dsm_opt_vmcuser: ""
  dsm_opt_vmdefaultdvportgroup: ""
  dsm_opt_vmdefaultdvswitch: ""
  dsm_opt_vmdefaultnetwork: ""
  dsm_opt_vmenabletemplatebackups: ""
  dsm_opt_vmlimitperhost: ""
  dsm_opt_vmmaxbackupsessions: ""
  dsm_opt_vmmaxrestoresessions: ""
  dsm_opt_vmmc: ""
  dsm_opt_vmnocbtcontinue: ""
  dsm_opt_vmnoprdmdisks: ""
  dsm_opt_vmnovrdmdisks: ""
  dsm_opt_vmprocessvmwithindependent: ""
  dsm_opt_vmprocessvmwithprdm: ""
  dsm_opt_vmskipctlcompression: ""
  dsm_opt_vmverifyifaction: ""
  dsm_opt_vmverifyiflatest: ""
  dsm_opt_vmtimeout: ""
  dsm_opt_wildcardsareliteral: ""

dsm_opt_optfile_path: "/opt/tivoli/tsm/client/ba/bin/dsm.opt"
dsm_opt_optfile_path_windows: 'C:\Program Files\Tivoli\TSM\baclient\dsm.opt'
dsm_opt_state: "present"
