# Defaults for sp_server_facts role
sp_server_facts_flags:
  q_status: true
  q_monitorsettings: true
  q_db: false
  q_dbspace: false
  q_log: false
  q_domain: false
  q_copygroup: false
  q_replrule: true
  q_devclass: false
  q_mgmtclass: true
  q_stgpool: true

