---
- name: Upgrade SP Server
  hosts: all
  become: true
  roles:
    - ibm.storage_protect.sp_server_install
  vars:
    sp_server_state: "upgrade"
    sp_server_bin_repo: "/path/to/the/repo/on/control/node"
    sp_server_version: "8.1.25"
...
