# Default values for dp_db2_postcheck role

# This is the user under which the DB2 instance runs.
db2_instance_owner: "" # DB2 instance owner

# Current password for IBM Storage Protect API
# It is used to authenticate and set a new password for IBM Storage Protect.
storage_protect_current_password: ""

# New password for IBM Storage Protect API
# It is used to set a new password for IBM Storage Protect.
storage_protect_new_password: ""